update again

diff --git a/.github/workflows/olive-cicd-eks.yaml b/.github/workflows/olive-cicd-eks.yaml
--- a/.github/workflows/olive-cicd-eks.yaml
+++ b/.github/workflows/olive-cicd-eks.yaml
@@ -7,7 +7,9 @@ permissions:
 
 on:
   push:
-    branches: [ "main"]
+    branches: [ "develop"]
+  pull_request:
+    branches: [ "develop"]
 jobs:
   verify_pipeline:
     environment: runner
@@ -31,6 +33,7 @@ jobs:
           --health-interval=10s
           --health-timeout=5s
           --health-retries=3
+
     steps:
     - name: 소스코드 다운로드
       uses: actions/checkout@v4 
@@ -40,3 +43,59 @@ jobs:
       with:
         java-version: '17'
         distribution: 'temurin'
+        
+    - name: change application.yml
+      run: |
+        cat > src/main/resources/application.yml << EOF
+        spring:
+          datasource:
+            url: ${{ secrets.DATABASE_URL }} # 예dbc:mysql://localhost:3306/istory
+            username: ${{ secrets.MYSQL_USER }}
+            password: ${{ secrets.MYSQL_PASSWORD }}
+            driver-class-name: com.mysql.cj.jdbc.Driver
+          jpa:
+            database-platform: org.hibernate.dialect.MySQL8Dialect
+            hibernate:
+              ddl-auto: update
+            show-sql: true
+          application:
+            name: USER-SERVICE
+          jwt:
+            issuer: user@gmail.com
+            secret_key: study-springboot
+        management:
+          endpoints:
+            web:
+              exposure:
+                include: health,info
+          endpoint:
+            health:
+              show-details: always
+        EOF
+    - name: 테스트 수행
+      run: ./gradlew test
+
+    - name: 테스트 검사 후 실패 시 파이프라인 중단
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
+
+    - name: 테스트 결과를 STEP Summary 에 업로드
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30 
+
+    - name: 기본 수행정보 Step Summary 에 표시
+      run: |
+        echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
